apiVersion: v1
kind: Pod
metadata: 
  name: us-project
spec: 
  volumes: 
   - name: html
     emptyDir: {}
  containers: 
   - name: 1st
     image: centos
     volumeMounts:
     - name: html
       mountPath: /usr/share/nginx/html
   - name: 2nd
     image: centos
     volumeMounts:
      - name: html
        mountPath: /html
     command: ["/bin/sh","-c"]
     args:
      - while true; do
         date >> /html/index.html;
         sleep 10;
        done
