apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-server
  labels:
   app: db-server
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
     app: db-server
  template:
    metadata: 
     labels:
      app: db-server
    spec:
     containers:
      - name: nginx
        image: nginx:1.9.1
        ports:
        - containerPort: 80
