apiVersion: v1
kind: LimitRange
metadata:
   name: limit-mem-cpu-per-container

spec:
   limits:
     - max:
         cpu: "800Mi"
         memory: "1Gi"
       min:
         cpu: "100Mi"
         memory: "100Mi"    
       default:
         cpu: "700Mi"
         memory: "900Mi"
       defaultRequest: 
         cpu: "150Mi"
         memory: "111Mi"
       type: Container


