apiVersion: v1
kind: PersistentVolume
metadata:
  name: reliance-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: reliance-volume
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /common/volume
    server: 10.190.0.3
