apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reliance-rpower
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: reliance-volume
