apiVersion: v1
kind: ResourceQuota
metadata:
        name: project1-quota
        namespace: project1
spec: 
   hard:
      pods: "2"
      configmaps: "10"
      secrets: "10"
      services: "10"
      persistentvolumeclaims: "50"
      limits.memory: "800Mi"
      limits.cpu: "10"

