apiVersion: v1
kind: ReplicationController
metadata:
   name: rajneesh
spec:
   replicas: 5
   selector:
     team: dev
   template:
     metadata:
      name: rajneesh
      labels: 
        team: dev
     spec:   
      containers:
         - name: raju
           image: nginx:1.11.1
           ports:
            - containerPort: 80
