apiVersion: v1
kind: ReplicationController
metadata:
  name: cloudknowledges
spec:
  replicas: 3
  selector:
    team: dev
  template:
    metadata:
      name: cloudknowledges
      labels:
        team: dev
    spec:
      containers:
      - name: cloudknowledges
        image: nginx:1.7.1
        ports:
        - containerPort: 80	
